Update sync-dev.yml

diff --git a/.github/workflows/sync-dev.yml b/.github/workflows/sync-dev.yml
--- a/.github/workflows/sync-dev.yml
+++ b/.github/workflows/sync-dev.yml
@@ -1,23 +1,37 @@
-name: Upstream Dev Sync 
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
-  workflow_dispatch:   
+  workflow_dispatch:
 
 jobs:
-  sync:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout target repo
-        uses: actions/checkout@v4
-        with:
-          ref: main         
-          fetch-depth: 0   
+    if: ${{ github.event.repository.fork }}
 
-      - name: Sync with Upstream
+    steps:
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
+        with:
+          upstream_sync_repo: ObexDNS/ObexDNS
+          upstream_sync_branch: dev
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
+
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
         run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git remote add upstream https://github.com/ObexDNS/ObexDNS.git
-          git fetch upstream dev
-          git merge upstream/dev
-          git push origin dev
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
